FROM node:23-bookworm AS webui
WORKDIR /app
RUN apt install -y make
COPY . .
RUN make webui

FROM golang:1.24 AS base

RUN groupadd -g 8433 relique && useradd -u 8433 -g 8433 relique 

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY --from=webui /app/webui/dist /app/internal/server/dist
RUN make bin

RUN cp /app/output/relique /bin/relique
RUN relique config init

RUN go vet ./...
RUN go test -cover ./...