port = 8434
bind_addr = "0.0.0.0"

ssl_cert = "/etc/relique/certs/cert.pem"
ssl_key = "/etc/relique/certs/key.pem"
strict_ssl_certificate_check = true

module_install_path = "/var/lib/relique/modules"
