name: Docker Images build

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF##*/})
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          push: true
          file: build/package/Dockerfile
          tags: |
            macarrie/relique:latest
            macarrie/relique:${{steps.vars.outputs.tag}}
          platforms: |
            linux/amd64
            linux/arm64
